# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191127_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='location',
            new_name='value',
        ),
    ]
